FROM openjdk:8
MAINTAINER Peter Pan
LABEL app="cm4e" version="0.0.1" by="Peter"
ADD ./target/dudumall-backend-merchandise-service-0.0.1-SNAPSHOT.jar dudu-merchandise.jar
EXPOSE 8081
CMD java -jar dudu-merchandise.jar

