FROM openjdk:8
MAINTAINER Peter Pan
LABEL app="dudumall-backend-user" version="0.0.1" by="Peter"
ADD ./target/dudumall-backend-user-service-0.0.1-SNAPSHOT.jar dudu-user.jar
EXPOSE 8080
CMD java -jar dudu-user.jar
